# Dependabot Configuration for Spotify MCP Server
# Automatically keeps dependencies up-to-date and secure

version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    reviewers:
      - "kholcomb"
    assignees:
      - "kholcomb"
    labels:
      - "dependencies"
      - "automated"
    target-branch: "development"
    
    # Enable auto-merge for patch and minor updates
    auto-merge:
      squash-merge: true
    
    # Group updates for better management
    groups:
      # Production dependencies
      production:
        patterns:
          - "@modelcontextprotocol/*"
          - "axios"
          - "dotenv"
          - "open"
          - "zod"
        
      # Development dependencies  
      development:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "jest*"
          - "prettier"
          - "ts-*"
          - "tsx"
          - "typescript"
        
      # Security-focused updates (higher priority)
      security:
        patterns:
          - "*"

    # Version update strategy
    versioning-strategy: increase
    
    # Ignore specific dependencies if needed
    ignore:
      # Ignore major version updates for core dependencies
      # to prevent breaking changes
      - dependency-name: "@modelcontextprotocol/sdk"
        update-types: ["version-update:semver-major"]
      
    # Rebase strategy for PR management
    rebase-strategy: "auto"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "kholcomb"
    assignees:
      - "kholcomb"
    labels:
      - "github-actions"
      - "ci-cd"
      - "automated"
    target-branch: "development"

  # Monitor Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "docker"
      include: "scope"
    reviewers:
      - "kholcomb"
    assignees:
      - "kholcomb"
    labels:
      - "docker"
      - "infrastructure"
      - "automated"
    target-branch: "development"